name: Python package

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: poetry install
      - name: generate code
        run: |
          poetry run ldraw download --version 2018-02 --yes
          poetry run ldraw generate --destination .generated-cache
      - uses: actions/upload-artifact@master
        CACHE_DIR:
        with:
          name: generated-ldraw-library
          path: .generated-cache

  test:
    needs: generate
    runs-on: ubuntu-latest
    env:
      LDRAW_GENERATED_PATH: .generated-cache
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: snok/install-poetry@v1.1.1
    - name: Install dependencies
      run: poetry install

    - uses: actions/download-artifact@master
      with:
        name: generated-ldraw-library
        path: .generated-cache

    - name: Test with pytest
      run: pytest --cov=ldraw
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
      run: coveralls

  publish:
    needs:
      - test
      - generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: dschep/install-poetry-action@v1.3
    - name: Install dependencies
      run: poetry install

    - uses: actions/download-artifact@master
      with:
        name: generated-ldraw-library
        path: .generated-cache

    - name: Build package
      run: |
        poetry build -vv
    - name: test upload
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: |
        poetry publish -r https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.testpypi_password }}
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        poetry publish -u __token__ -p ${{ secrets.pypi_password }}


  cleanup_job:
    needs: publish
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: call webhook to delete artifacts
      env:
        FOR_WEBHOOKS_SECRET: ${{ secrets.FOR_WEBHOOKS_SECRET }}
      run: |
        echo "::add-mask::$FOR_WEBHOOKS_SECRET"
        curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"
